services:

  kafka-producer:
    environment:
      SPRING_PROFILES_ACTIVE: secondary
      KAFKA_BOOTSTRAP_SERVERS: kafka-secondary:9092
      SCHEMA_REGISTRY_URL: https://schema-registry-secondary:8082
    depends_on:
      kafka-secondary:
        condition: service_healthy
      schema-registry-secondary:
        condition: service_healthy

  kafka-consumer:
    environment:
      SPRING_PROFILES_ACTIVE: secondary
      KAFKA_BOOTSTRAP_SERVERS: kafka-secondary:9092
      SCHEMA_REGISTRY_URL: https://schema-registry-secondary:8082
    depends_on:
      kafka-secondary:
        condition: service_healthy
      schema-registry-secondary:
        condition: service_healthy
